### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by CRAFTBOYPE** [SalmonCraftPE/ClearSkyFork#2]
`Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar://C:/Users/User/Desktop/ClearOcean-master/ClearOcean.phar/src/pocketmine/Server.php on line 87`

This error pops out when i start the Server

**Comment by SalmonGER** [comment]
ClearOcean is currently on php5. Do you use PHP5?

**Comment by Aericio** [comment]
Please use PHP5 and not PHP7

**Comment by CRAFTBOYPE** [comment]
I re-installed it now it works fine
